### ISSUE TITLE
Newest release NoClassDefFoundError

### ISSUE THREAD

**Issue by Selbi182** [spotify-web-api-java/spotify-web-api-java#363]
Just tried to update from 8.0.0 to the newest release (I wanted to see if [this](https://github.com/spotify-web-api-java/spotify-web-api-java/pull/345) does anything on my end) but I can't launch my app anymore, as I get the following error during launch:

```
Caused by: java.lang.NoClassDefFoundError: org/apache/hc/client5/http/config/ConnectionConfig
	at se.michaelthelin.spotify.SpotifyHttpManager.<init>(SpotifyHttpManager.java:79) ~[spotify-web-api-java-8.3.3.jar:na]
	at se.michaelthelin.spotify.SpotifyHttpManager$Builder.build(SpotifyHttpManager.java:406) ~[spotify-web-api-java-8.3.3.jar:na]
	at se.michaelthelin.spotify.SpotifyApi.<clinit>(SpotifyApi.java:77) ~[spotify-web-api-java-8.3.3.jar:na]
	at se.michaelthelin.spotify.SpotifyApi$Builder.<init>(SpotifyApi.java:1888) ~[spotify-web-api-java-8.3.3.jar:na]
	at spotify.api.SpotifyApiManager.createSpotifyApi(SpotifyApiManager.java:85) ~[spotify-dependencies-1.10.1.jar:na]
	at spotify.api.SpotifyApiManager.spotifyApi(SpotifyApiManager.java:79) ~[spotify-dependencies-1.10.1.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.30.jar:5.3.30]
	... 47 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.hc.client5.http.config.ConnectionConfig
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	... 58 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:50695', transport: 'socket'

Process finished with exit code 1
```

I saw some mentions of Java 21. Is that the newest minimum required version? Because I'm still on 11.

Furthermore, I use Spring 2.7.7, so maybe it's some version conflict internally?

**Comment by dargmuesli** [comment]
No such changes happened in v`8`, there was only a somewhat-breaking feature and some housekeeping: https://github.com/spotify-web-api-java/spotify-web-api-java/releases/tag/8.0.0

Are you coming from v`7.3.0`? Does v`7.3.0` work for you? Most past issues mentioning `NoClassDefFoundError` were related to some faulty dependency setup / caching.

**Comment by Selbi182** [comment]
I upgraded from 8.0.0 to 8.3.3 and I didn't have any class def issues for over two years of using this library (including 7.3.0).

**Comment by dargmuesli** [comment]
So, `8.3.3` works for you now?

**Comment by Selbi182** [comment]
No... we seem to have a communication problem here. So from the top: I've been using 8.0.0 for a long time now and saw you made a bunch of new releases in one day recently, so I upgraded. But it doesn't work, because of that NoClassDefFoundError.

While I still don't understand why you made so many releases at once, I just tested them one by one. Turns out it's the specific jump from 8.2.1 to 8.3.0 that's the cause.

**Comment by dargmuesli** [comment]
I see. Could you share a minimal reproduction with me? Like a repo with only Gradle set up and the minimal changes required to demonstrate this issue? I think of something like [stackblitz](https://stackblitz.com/), but for Java.

**Comment by Selbi182** [comment]
Uhh, I don't know what that is. But I guess you could clone my project that uses your wrapper and change the dependency to 8.3.3? https://github.com/Selbi182/SpotifyBigPicture/blob/master/build.gradle#L50C73-L50C73

**Comment by dargmuesli** [comment]
Seems like a bug in the http client. I've released an update to the most recent version in v8.3.4 which should be available on maven central shortly.

**Comment by Selbi182** [comment]
Unfortunately, the problem persists in 8.3.4:

![grafik](https://github.com/spotify-web-api-java/spotify-web-api-java/assets/8850085/b7a7193f-deb3-41f4-9dcd-ed4b67949c15)

**Comment by dargmuesli** [comment]
I think that could be related to `spotify:spotify-dependencies:1.10.1` which uses v8.0.0.

**Comment by Selbi182** [comment]
Nope, updating that didn't fix it either. I'll just keep the explicit version force of the httpclient to 5.2.1 for now. Maybe there's some weird Gradle quirk going on with version conflicts.
